apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop-demo
  template:
    metadata:
      labels:
        app: crashloop-demo
    spec:
      containers:
        - name: broken-container
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting app..."
              sleep 2
              echo "Crashing now!"
              exit 1